languge: node_js

cache:
  directories: 
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script: 
  - yarn build

notifications:
  notifications:
  slack: workspace:token
  email:
    - rcaballero082@gmail.com  
  on_succes: always
  on_failure: always


deploy: 
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN2 
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy de proyecto :)"
  on:
    branch: master
